config/routes.rb
Rails.application.routes.draw do
  resources :tacos

  root 'tacos#home'

end

app/models/taco.rb
class Taco < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tacos_controller.rb
class TacosController < ApplicationController
  before_action :set_taco, only: [:show, :edit, :update, :destroy]

  def home
  end
  

  # GET /tacos
  # GET /tacos.json
  def index
    @tacos = Taco.all
  end

  # GET /tacos/1
  # GET /tacos/1.json
  def show
  end

  # GET /tacos/new
  def new
    @taco = Taco.new
  end

  # GET /tacos/1/edit
  def edit
  end

  # POST /tacos
  # POST /tacos.json
  def create
    @taco = Taco.new(taco_params)

    respond_to do |format|
      if @taco.save
        format.html { redirect_to @taco, notice: 'Taco was successfully created.' }
        format.json { render :show, status: :created, location: @taco }
      else
        format.html { render :new }
        format.json { render json: @taco.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tacos/1
  # PATCH/PUT /tacos/1.json
  def update
    respond_to do |format|
      if @taco.update(taco_params)
        format.html { redirect_to @taco, notice: 'Taco was successfully updated.' }
        format.json { render :show, status: :ok, location: @taco }
      else
        format.html { render :edit }
        format.json { render json: @taco.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tacos/1
  # DELETE /tacos/1.json
  def destroy
    @taco.destroy
    respond_to do |format|
      format.html { redirect_to tacos_url, notice: 'Taco was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_taco
      @taco = Taco.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def taco_params
      params.require(:taco).permit(:name, :meat, :topping, :salsa, :cost, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tacos_helper.rb
module TacosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Uno Mas Taco Shop</title>

  <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous">

<link href='https://fonts.googleapis.com/css?family=Droid+Serif' rel='stylesheet' type='text/css'>

<link href='https://fonts.googleapis.com/css?family=Arvo:400,400italic' rel='stylesheet' type='text/css'>


  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

		<nav class="navbar navbar-default">
	  <div class="container-fluid">
	    <!-- Brand and toggle get grouped for better mobile display -->
	    <div class="navbar-header">
	      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	      <a class="navbar-brand" href="#"><span class="label label-danger">Taco Tipos</a>
	    </div>

	    <!-- Collect the nav links, forms, and other content for toggling -->
	    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	      <ul class="nav navbar-nav">
	        <li class="active"><a href="#"><span class="label label-danger">Location, Info and Pix</span></a></li>
	        <li><a href="#"><span class="label label-danger">Swag</a></li>
	        <li class="dropdown">
	          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="label label-danger">Social Media<span class="caret"</span></a>
	          <ul class="dropdown-menu">
	            <li><a href="#"><span class="label label-danger">Instagram</a></li>
	            <li><a href="#"><span class="label label-danger">Facebook</a></li>
	            <li><a href="#"><span class="label label-danger">Four Square</a></li>
	            <li><a href="#"><span class="label label-danger">Twitter</a></li>
	            <!-- <li role="separator" class="divider"></li> -->
	            <li><a href="#"><span class="label label-danger">Flickr</a></li>
	            <!-- <li role="separator" class="divider"></li> -->
	            <li><a href="#"><span class="label label-danger">Yelp</a>

	          </ul>
	        </li>
	      </ul>
	      
	     <!--  -->
	    </div><!-- /.navbar-collapse -->
	  </div><!-- /.container-fluid -->
	</nav>


	<%= yield %>

		
		<nav class="navbar navbar-default">
		  <div class="container-fluid">
		    <div class="navbar-header">
		     <!--  <a class="navbar-brand" href="#"> -->
		        <img class="icon" alt="Brand" src="http://betaboston.com/wp-content/uploads/2014/06/taco-emoji.png">
		      </a>
		    </div>
		  </div>
		</nav>



	</body>

<footer>
<p class="foot"> &copy; 2015 Fireal, Luckey Road Designs   -  G. Marc Benavidez</p>


</footer>

	<!-- Latest compiled and minified JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js" integrity="sha512-K1qjQ+NcF2TYO/eI3M6v8EiNYZfA95pQumfvcVrTHtwQVDG+aHRqLi/ETn2uB+1JqwYqVG3LIvdm9lj6imS/pQ==" crossorigin="anonymous"></script>

	</html>

app/views/tacos/_form.html.erb
<%= form_for(@taco) do |f| %>
  <% if @taco.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@taco.errors.count, "error") %> prohibited this taco from being saved:</h2>

      <ul>
      <% @taco.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :meat %><br>
    <%= f.text_field :meat %>
  </div>
  <div class="field">
    <%= f.label :topping %><br>
    <%= f.text_area :topping %>
  </div>
  <div class="field">
    <%= f.label :salsa %><br>
    <%= f.text_area :salsa %>
  </div>
  <div class="field">
    <%= f.label :cost %><br>
    <%= f.number_field :cost %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tacos/edit.html.erb
<h1>Editing Taco</h1>

<%= render 'form' %>

<%= link_to 'Show', @taco %> |
<%= link_to 'Back', tacos_path %>

app/views/tacos/home.html.erb
<div class="jumbotron">

<center>
 
 <h1 class="title">Uno Mas Taco Shop</h1>

 <h2 class="title">Dallas, Texas</h2>

 <img src="http://stuffstonerslike.com/wp-content/uploads/2009/02/stoners-like-taco-bell.gif">

 <br>
 <br>

 <%= link_to "Our Tacos", tacos_path, class: "btn btn-default" %>

 </center>

 </div>

app/views/tacos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tacos</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Meat</th>
      <th>Topping</th>
      <th>Salsa</th>
      <th>Cost</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tacos.each do |taco| %>
      <tr>
        <td><%= taco.name %></td>
        <td><%= taco.meat %></td>
        <td><%= taco.topping %></td>
        <td><%= taco.salsa %></td>
        <td><%= taco.cost %></td>
        <td><img src="<%= taco.image %>"</td>
        <td><%= link_to 'Show', taco %></td>
        <td><%= link_to 'Edit', edit_taco_path(taco) %></td>
        <td><%= link_to 'Destroy', taco, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Taco', new_taco_path %>

app/views/tacos/new.html.erb
<h1>New Taco</h1>

<%= render 'form' %>

<%= link_to 'Back', tacos_path %>

app/views/tacos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @taco.name %>
</p>

<p>
  <strong>Meat:</strong>
  <%= @taco.meat %>
</p>

<p>
  <strong>Topping:</strong>
  <%= @taco.topping %>
</p>

<p>
  <strong>Salsa:</strong>
  <%= @taco.salsa %>
</p>

<p>
  <strong>Cost:</strong>
  <%= @taco.cost %>
</p>

<p>
  <strong>Image:</strong>
 <img src="<%= @taco.image %>">

</p>

<%= link_to 'Edit', edit_taco_path(@taco) %> |
<%= link_to 'Back', tacos_path %>